### ISSUE TITLE
Does the SCD4x forced recalibration snippet use `persist_settings`?

### ISSUE THREAD

**Issue by Aariq** [Sensirion/arduino-snippets#3]
I'm not super familiar with Arduino code and I'm trying to figure out if the [forced recalibration SCD4x snippet](https://github.com/Sensirion/arduino-snippets/blob/main/SCD4x_I2C_FRC_Forced_Recalibration_Example/SCD4x_I2C_FRC_Forced_Recalibration_Example.ino) is something I can just run once, then switch back to the usual periodic measurement script provided in the [tutorial I followed](https://learn.adafruit.com/diy-trinkey-no-solder-air-quality-monitor/arduino-code).  Will the calibration persist?  If not, how can I edit the re-calibration code to turn this feature on?

**Comment by Fototux** [comment]
The forced recalibration is persistent. Once applied the value is stored in the EEPROM. 

It is recommended to run the sensor for at least 3 min to stabilize. Then the snippet code can be applied (line 100 to line 150: stop measurement, send calibration data, check return value). Then you can switch on again the periodic measurement again as  shown in the tutorial.

**Comment by Aariq** [comment]
Thanks
