### ISSUE TITLE
Integer Overflow in  SCD4x_I2C_FRC_Forced_Recalibration_Example.ino

### ISSUE THREAD

**Issue by daveTheWizzard** [Sensirion/arduino-snippets#7]
Line 63 in SCD4x_I2C_FRC_Forced_Recalibration_Example.ino causes an integer overflow:
`delay(5 * 60 * 1000);`
In an Arduino Uno and other ATmega based boards the maximum value for an int is 32,767.  Consequently, 5 * 60 * 1000 gets evaluated to a negative number and the delay never terminates.
Possible solution:
`delay(5 * 60 * (long)1000);`

**Comment by psachs** [comment]
thanks for pointing out the issue. In fact Arduino uno will work with 16-bit integers and needs an explicit cast to unsigned long (the expected data type of delay) to avoid potential overflows.

The issue is fixed on master
